pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - and:
          - author=dependabot[bot]
          - check-success=Code QL
          - check-success=Run CI
          - check-success=dependency-review
          - check-success=SonarCloud
          - check-success~=^security/snyk
          - or:
              - title~=^chore\(deps\). [w+]|[^\s]+ from ([\d]+)\..+ to \1\.
              - title~=^feat\(deps\). [w+]|[^\s]+ from ([\d]+)\..+ to \1\.
              - title~=^build\(deps\). [w+]|[^\s]+ from ([\d]+)\..+ to \1\.
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot
      merge:
        method: rebase