name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  cypress-run:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository for cypress tests
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Use Node.js current version
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: current

      - name: Install package dependencies
        run: npm ci

      - name: Run cypress test
        uses: cypress-io/github-action@4d475873e011991664253f34700acfc3acdc46a3
        with:
          browser: chrome
          install: false
          build: npm run cypress:build
          start: |
            npm run demo:dev
            npm run demo:prod
