name: CI

on: [pull_request]

permissions: read-all

jobs:
  cypress-run:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository for cypress tests
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Use Node.js current version
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: current

      - name: Install package dependencies
        run: npm ci

      - name: Build module
        run: npm run build
      
      - name: Prepare demo project for testing
        run: npm run demo:clean

      - name: Run cypress to test behavior during development
        uses: cypress-io/github-action@c5724eda82337bcff977ce14509f47052c12e04c
        with:
          browser: chrome
          start: npm run demo:dev

      - name: Run cypress to test behavior in production
        uses: cypress-io/github-action@c5724eda82337bcff977ce14509f47052c12e04c
        with:
          browser: chrome
          build: npm run demo:prod
