name: CodeQL

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  codeql:
    name: Code QL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository for code analysis
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Initialize CodeQL
        uses: github/codeql-action/init@807578363a7869ca324a79039e6db9c843e0e100
        with:
          languages: javascript
          queries: security-extended

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@807578363a7869ca324a79039e6db9c843e0e100
